services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://kafka:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      test: [
        "CMD-SHELL", 
        "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"
      ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - bridge

  flask:
    build: flaskapp
    container_name: flask
    ports:
      - "5000:5000"
    env_file:
      - flaskapp/.env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - bridge

  postgres:
    build: postgres
    container_name: postgres
    shm_size: 128mb
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - bridge

  producer:
    build: pythonapp
    container_name: producer
    command: python -m pythonapp.apps.produce --stream kline_1s --symbols btcusdt # ethusdt xrpusdt
    env_file:
      - pythonapp/.env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - bridge

  inserter:
    build: pythonapp
    container_name: inserter
    command: python -m pythonapp.apps.insert --stream kline_1s
    env_file:
      - pythonapp/.env
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - bridge

#  calculator:
#    build: pythonapp
#    container_name: calculator
#    command: python pythonapp/apps/calculate.py
#    env_file:
#      - pythonapp/.env

networks:
  bridge: