# Generated by Django 4.2.23 on 2025-07-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_time', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=20)),
                ('is_closed', models.BooleanField()),
                ('start_time', models.BigIntegerField()),
                ('close_time', models.BigIntegerField()),
                ('first_trade_id', models.BigIntegerField()),
                ('last_trade_id', models.BigIntegerField()),
                ('open_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('trade_count', models.BigIntegerField()),
                ('volume_base', models.DecimalField(decimal_places=10, max_digits=30)),
                ('volume_quote', models.DecimalField(decimal_places=10, max_digits=30)),
                ('taker_volume_base', models.DecimalField(decimal_places=10, max_digits=30)),
                ('taker_volume_quote', models.DecimalField(decimal_places=10, max_digits=30)),
                ('saved_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'kline_1s_processed',
                'managed': False,
            },
        ),
    ]
